---
# some created directories may be redundant, but are kept in case anything else
# changes, and to enable the picking and choosing of components/roles.
- name: create consul configuration directory
  sudo: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - consul
    - distributive

- name: copy distributive consul test
  sudo: yes
  copy:
    src: distributive-consul-check.json
    dest: /etc/distributive.d/consul.json
    mode: 0664
    owner: root
    group: root
  tags:
    - distributive

- name: register distributive tests with consul
  sudo: yes
  copy:
    src: distributive-consul-config.json
    dest: /etc/consul
  notify:
    - reload consul
  tags:
    - consul
    - distributive

- name: run distributive consul test
  sudo: yes
  command: /usr/bin/distributive -f /etc/distributive.d/consul.json
  tags:
    - consul
    - distributive
