---
- hosts: all
  vars:
    consul_servers_group: role=control
    consul_dns_domain: consul
    consul_dc: vagrant
    consul_acl_datacenter: vagrant
    consul_bootstrap_expect: 1
    mesos_cluster: vagrant
    mesos_mode: mixed
    private_ipv4: "{{ ansible_default_ipv4.address }}"
    public_ipv4: "{{ ansible_default_ipv4.address }}"
    provider: vagrant
  roles:
    - common
    - collectd
    - logrotate
    - consul-template
    - docker
    - dnsmasq
    - nginx
    - consul
    - logstash
    - vault
    - zookeeper
    - mesos
    - marathon
    - chronos
