---
- name: clean hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item }}"
    state: absent
  with_items:
    - "^127.0.0.1 {{ inventory_hostname }}.*"
    - "^::1 {{ inventory_hostname }}.*"
